language: java
sudo: false
env:
    global:
        #key for github
        #GITHUB_OAUTH_TOKEN
        - secure: "wqNF4mjFjgoBHKScsVWS3uXwx+vBedaroX0881zTCUeECDHM8zUe7beaNPk346GjLEx7HOM4K4+pikec+QhwBziDTsay6TIZ3gV00mhtqIJbNT6rPHQCCKEX6q21M/yjTasmvvUwPKUAQY9S8ojqpU49BP+EYxygn/BgFn72JqAsW8YKXpSOH4521IfellIR2XBpWX3jLWpYOuEwunuSE41nAP8bF23/BmaPEe7SKauxWEeOk7NBbANh8tfUnsVzw4GHiax3A9JqVvcGXeys5KBZWw4qaHYDuHU5ydtDnEHA+Ryeq6zrrNbbcBDr2ABZZoRtCk9/JY434w7elD2C9NNaby17JJr/jHVIyj6iMy1nIXFeyVyWaOSPDimIgZ/wVHGswAGcAsx/sNSJHlrVLnzvcRQyPV6VILSpEuvWRjMZgXdqGoS6dku5yENHt28cO7+3tRV7kB6VYE/fF4fq4nL6hSbNZSqB2+I4xZ4CMi52qEgB+G/oSMzbT+/jKZSEh3iAHv2smnU+jqjEsN92OKS7HV8wnAM15lf2WxnlMfBw39T3KErrA4UDx9DZiwm5tJLGXKMo+heslXwm5sG8Wi1WHahuTfJbXUA6ut7lcNoGiRDFgfhDhN65PLtRCfItyxMZYkehT1NxYZELumgSYaS+tZOtkp/ikfGUU1msfig="
        - environment=test
        #sonatype credentials
        #OSSRH_JIRA_USERNAME
        - secure: "3CdqMC+ReXh5j9hrY7i9quED0jMpJTbTfNq7NLNsjAzOTIXXYVnRCDoWOe/d5zB60LXUJdvbL1pw7rDdsdTzdVrRT5WmqywsRDgINZlcuMT0pTYdlYtNrgecJ53NLwPCi0FEuvSYoyDdnzuKtqrWBpImmyAeXypUPEIgekTLKSZdaEvUI924GkzjpuMiRiU0VeyyAjF27fvTymCVtOr3dsTngkGedb1yzmouTRZJMLLYAnq+SV6SU0PtceqUV7egk5AA2uzeV2g/ODpMOAiUYnW78SpTE7Sk4H+YvVKtBVlHQCQpvC4AFcyqzNrMl8BFAc29jD7vbIH9HtSMOhsXEziidOQILrC8kWtIm+z5CT+swGaWntpwdyQ6wkO4Vk0a530iApvMAtLZ2b3UdhPa7FAA3zC/oG+9XeOA1w+uY3jFzFLhiRFtHUuFdIopEA+diI4xDfoe7eC1p38bRWulTO2eGLoMudRdALYzKtUBo70Ssr7gpj2ukZV4tiNyZhBuEa8Fop+DJ78UglXsm/0z8/C801lAtaqrcRNZh+Ak+6PIMJLUFkiN4kJAMdQ8VtjzKiDpCUBZq1g3uVL4UExQ8HpDDhg4srADcbLzlGSiIWI9ae1hbcA21QsV4LKFkbohX5d3f46Vq48I8AbcIwzViR89le+KnJK01L5X+Pc/6Xk="
        #OSSRH_JIRA_PASSWORD
        - secure: "papJ+GbHZTYPrKT6X6DZnbH1Z2F6J3s+NnLPIjj6baL0VnQLjE5G3WHp37tqh0vgotjqRemGsjIi+ZrQru80Uh0jaj0e9POwn8XUsoFXQS+A5+zc4cvo02QCq6420+PaHGuYOcQs42Neg/q9zccob9fPe96T+iCZ2iQm4UxU59QQfYH78lcdIk4vV1xxpSS49NC/XsyHd917+FzNh28Tezbduxzft6k7rIFRJIdWpzVcxaEsPlDd1d2eLgVWnGQntFhfvrIsygbcXhsRxzzCA+F2j/JxXhjstcOFyZgLO294oMais5FkC/JJFnU0Z32PdKIVG/8fGiK+s0q28ER4UkC+Z5f6Wy7kgUCJzNVmkva9IrRmGE3Kf30p7iGprAZ8yxYLwWWXN4GJPFWhga4XVoTa6kysSv8p8RmKk1Tx5Sp5KJuIP7kNMWTae7wHEfCMIS+LaLoVSYkQXFcrGvJZc+hg2LWItVAd3PzdKwVEe4351Dct9n1riLFEAp+d48Cbo+VWYa8BOd/P+KlB3r3ZGc0Pr9Bkpg9OnBR0B7FIz7xXQ74eP380k5RL2MTTPn0DPLusTL7w6/KfV47Qv+0jhfkIDpVvGVPfZ2RtTzcBjqo7ZQwvBAyobhX/GpPdfOOS/BiY6WQOA+Me3vkvFMAbK/19MLFz5GknLtH2dd399MM="
        #signing key
        #GPG_KEY_NAME
        - secure: "rD4CsZZXY72p1oHTRz6bcHHSGZZMI8TEe3WU+c65uUqZqoNP1Mgmy1XqD6nMjIwTCt11GQDnQVNlur6zTRrEHbFzsXI/DayxD/ezX15dOLnBB7bJVIMFCjtcpq5yRBB/rwQ7accnvTUDZWiJSyos3yvE0cVumAdM3yWzYP576Dfk3VcVY/EDNVPj6+GIboOevNhspiE6Lpqki8gQB8bdmZNnOQdsJZcNipG82ln6J/AlHvrKTZDhKBT5ww//Pm9R2+4S0A/tYFrSiw+AX7Zei2u6K3vB9Kxt+j3dvSuwWOM4GK5zZmgOrrDs/SYg2U2rO7GeqmCJVtmQlY0opChGhnpZQtlufSpWMP+d/ArH6qjddSbGbX/oGoubfA11P3laS5b9GlYBvc3cwuLpK+pAii/Yd6zxfOF2plu/YJkHbmhH0oE79tpB+s3hZVyWmoyrCJu+6Ck4aCP5SBIEfktOZ+QE1XCBk/KmiIEHevkKK9rSWF0nFkReBVhMJiAhjOnrFc2CFhCJxx6OycC5iYAuqpAOW1epcMvlqxxcegW2dV5y2+WKM8+rPX95NbNu1gBjhQrvOMa56nOHdlY57h+pB5ZdnmtVouSuGY9jaEI+n8xVUdfdcaehcktEMM3rKbN4ImoJkpRWc7vN5FQl61cVD9QSpwf7QJA/8IjZZ+nheWU="
        #GPG_PASSPHRASE
        - secure: "e4Ts7yzhrJyzKhdIdwpYxLMs4JwnxUiqM9NghTvxA/toEYr1Bl9UBizHKiZVK1rireT7CdpZdM2Cpt2xWcaz7qdBic8CYT5EG0pQA/uUgupAhwNetjib0b42z0CgykqUUF05B6JpmbTAz4l9U1fipYL5fQN+XJRnoDFCdRKU8KDpTOTHzwUrZwP21tssaxQo6306DdqYgQQsiYvlMdwfonRIBNv1D8htwz6dAo772PrZn8Iu+NfrUzbs85JgM2Lv+QLAHiuN4LESBnJL3N1DNcygrYs6fKCaFWGJlqGcuPEbDDSdF+8EuaO/EvP7l0qrjBsujOawMAmYaMgcx797WMejcBK0xfs/F5GYlfEqmRrX/raoqmlrUVBXUpSkgTmhqXZF8pIUkeUDf9439lx42YB4kHtYaiAxO2N8BoGbgJaMlw5pNyyjwlUG22vaYGImgKEIml+kg2vMiC9eWl++jqYxQTDHeOslD7wUwqros377X8gTlbK0C4ajrxT9cljNtXzBAZ9jCL0xIKjkv155k6ddQYvZYbAYTkVMR05VoJCrcypxbowJHCjBikB643xWhwcjfShqHhn3Lcs26OncQ76qCHt14qdrN5GAda3dqkOgSKQVpZLuEKXBsN0ee4qntbuqN97qo1b2ZzvKtwuM4VYgvYu53AhGo6cI++w+AoA="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "ycMpVSufEBmhaS4N1N3tK3XZLUYqnyYmwmzrYmBREdybQuGWW66jS9s/FhvvXdPvul8vIx0ydfcPT+XMdlkKMrW+ZPIw/yCz3kR8LKzy9Ecz+YQBXCI9SfwZHuzLqZdEnRQJ2wIuuY72Ssqvvpb/wohLO/ZkuX8CsT5LXa5lrooFH6D63GxobJca3kEDEY+XvygBn4ArB7EQYhoFo6BCql8Mh0TRnyMFCJGGZlOmQl1gYVi+VWxMtWXnIqHTFjiZyxdB3tCDQah2xMt3HSsBtOnhuf3FXtlatJbGBJBoROt/GDrGCicn7NeEZSxH8Vm8LEdlKEJo+3EvvlpfSz7xsPL29pERVnI5WHID5eTRl44Op6Z85SzsyaHjS1biL2SQesiZ+WDW6IxDCqD+b8kVi59CEhV2S3KEhKARtghZZGOpIXmzQfZFe4POY4p9hGbtJJ72ihLLZndZCU5oaIcDdwVngsu+goWWU3auQCMdX/kbHXaLYYbUbrM7AzaXqoR4hI9PjvYp8TfKJlN27psxqFy3eRJXmFWq7pUuMyLpe9H7reBx8C4CP9GChfVd6nJvZTrYBG8y4MKC0Hyvpj+noGlBn2VDk3vLBEFKGL9O6d4h/5XNNnZuffMtq6X2uC4lTXFWDThl3g5HGDcxP6EXp8HQoc8rK0N+4VxjctXzLo4="

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
  - mvn clean jacoco:prepare-agent install jacoco:report -Denvironment=test -P !build-extras
  - mvn site -Djacoco.skip -DskipTests -P !build-extras
  - sonar-scanner

cache:
  directories:
    - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: master

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh
